version: '3.7'
services:
  arangodb:
    image: arangodb/arangodb
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
      - DB_LINK_PORT_8529_TCP_ADDR=172.17.1.1
      - DB_LINK_PORT_8529_TCP_PORT=8529
    volumes:
      - ./docker/arangodb:/var/lib/arangodb3
    networks:
      project_net:
        ipv4_address: 172.27.1.1
  backend:
    image: docker.pkg.github.com/flymedllva/buildingplan/buildingplan-backend
    command: gunicorn app.main:app -w 6 -k uvicorn.workers.UvicornWorker --bind=0.0.0.0
    ports:
      - 8000:8000
    environment:
      ARANGODB_DATABASE_NAME: "_system"
      ARANGODB_DATABASE_URL: "http://172.27.1.1:8529"
    volumes:
      - ./docker/backend/backgrounds:/app/backgrounds
    networks:
      project_net:
        ipv4_address: 172.27.1.2
  frontend:
    image: docker.pkg.github.com/flymedllva/buildingplan/buildingplan-frontend
    command: npm start
    ports:
      - 80:5000
networks:
    project_net:
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/16

