name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Backend Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: flymedllva/buildingplan/buildingplan-backend
        username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        workdir: backend
    - name: Build the Frontend Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: flymedllva/buildingplan/buildingplan-frontend
        username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        workdir: frontend
    - uses: actions/checkout@v2
    - name: Build the Stack
      run: docker-compose up -d

